@baseUrl = http://localhost:3333


GET {{baseUrl}}/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXJ0aHVyIFNvdXNhIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jSm9HNXpRTXVfOGZHMzh3OHRLdHBISVhHdmZYU1h3U3BKQnR6R3YwSVpXX2d1a3dRPXM5Ni1jIiwic3ViIjoiY202bm12NXEwMDAwMGlvbXdpMXYxeDNnNiIsImlhdCI6MTczODUxNzAyMSwiZXhwIjoxNzM5MTIxODIxfQ.Fe2OGFSYx9FMF9sYE7m3P_ERRC5xlEgU-VUryHvKfMI

